### ISSUE TITLE
URL in sidebar needs to parse for lack of "http://"

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#1]
Because data will be user generated we can't assume users will know to preface https/http for URL, so will need (1) test for presence of properly formatted URL and as necessary (2) programmatically insert "http://" in the front.

**Comment by danhillcode** [comment]
Resolved. However, when we get to a stage when users are inputting points on the map it will be safer and better if we can format on entry rather than in a retrospective manner just to reduce potential bugs.

**Comment by kidwellj** [comment]
Agreed. And thanks!

**Comment by kidwellj** [comment]
Once you push the new code I'll mark as resolved. :)

**Comment by kidwellj** [comment]
Great. All set!
