### ISSUE TITLE
UX: dots, make smaller and lose border

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#11]
The opacity will work a bit better if we drop the border on these for now (I think). Can we also shrink the icon size by about 25%?

**Comment by danhillcode** [comment]
![pinkdots](https://user-images.githubusercontent.com/17653415/27793130-a9969d80-5ff4-11e7-9062-5f157383122a.png)

**Comment by danhillcode** [comment]
Does this look ok with the pink dots without border?

**Comment by danhillcode** [comment]
Yes changing the size is easy I just change the radius size to 7 should do it.

**Comment by kidwellj** [comment]
Yep - looking good. I think we could even increase opacity a bit more. Will also relate to https://github.com/mapcomm/common-ground_map/issues/10

**Comment by danhillcode** [comment]
![pink3](https://user-images.githubusercontent.com/17653415/27802655-063e32be-601d-11e7-9849-493fb2e42fe2.png)

**Comment by danhillcode** [comment]
lost the blue yay
