### ISSUE TITLE
UX: drop fields in panel if data is null or empty

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#13]
For fields like URL, Facebook, Twitter, etc. can we put in some code to test whether the field is null of empty and if so exclude completely from display? So some might just be "Name" and "Description" or whatever.

**Comment by danhillcode** [comment]
Just updated this so should be ok now for undefined fields however there is one of them that isn't playing ball Laurencekirk Development Trust near Aberdeen, not sure what the url is in there.

**Comment by danhillcode** [comment]
Also I didn't alter the description as it is being filled as suggested in last meeting.

**Comment by kidwellj** [comment]
Happy to report that Laurencekirk is "null" for url. :)
