### ISSUE TITLE
UX: set default map display to zoom level 7 and centred on middle of the UK

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#20]
Need to change default map state options for leaflet:
zoom = 7
center = [54, -40]

The goal is that an 800x600 map window should display the UK only with minimal seas / other features around

**Comment by danhillcode** [comment]
Added these co-ords, changed to 7 min zoom but it was too close 6 seems better to me layout wise. Index.html line 327 if you want to play/check it.

**Comment by kidwellj** [comment]
Perfect!
