### ISSUE TITLE
UX: add default text to display in right hand "information window" before point is clicked

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#21]
We need to add better placeholder data to display before user has clicked on a point in this window, i.e. "click on a point to display information including name, description, website, and neighbours about a group!"

**Comment by danhillcode** [comment]
so I have added this put think you may want to change this to your own input so line 157/158 is hwere it is located in the index.html file. plus do you want me to input sentences fr the walkthrough or do you have a script ready made for the walkthrough(clickthrough)?

**Comment by kidwellj** [comment]
This is perfect. I've got a whole script already written, just need to put in the time to get it set up. Will get this done later in the week.
