### ISSUE TITLE
CSS: Add padding for RH sidebar lower buttons so they are same as text above

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#24]
Currently the buttons in the bottom of the RH sidebar aren't padded. Need to add some whitespace so that their alignment matches that of the text above.

**Comment by danhillcode** [comment]
changed the buttons, Is the current push what you had in mind if not can you draw a picture and post it on here or slack.

**Comment by kidwellj** [comment]
Can you post commit sha here? Not sure which push you did it in! :) Is it 135218299e1b90ad77d353b096b4a8d51f75fc49?

**Comment by kidwellj** [comment]
Here ya go


<img width="380" alt="padding_example" src="https://user-images.githubusercontent.com/790736/30249628-b77689be-9637-11e7-851d-86efb1d10937.png">

**Comment by danhillcode** [comment]
Solved the problem with this but need to wait until I can click on a point to do the 'other groups nearby' as they only show after this but that will be the same fix. :)

**Comment by kidwellj** [comment]
Grand
