### ISSUE TITLE
Bug: "Additional Features" not displaying by default on LH sidebar

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#26]
For some reason, the top tab with colour and 'Additional Features' isn't loading on default, the user has to click a few times to open and close the sidebar before it will show.

**Comment by kidwellj** [comment]
![window_no_bar](https://user-images.githubusercontent.com/790736/29920634-2e383fc4-8e46-11e7-8fa6-2c1fea5ced50.png)

**Comment by danhillcode** [comment]
Is it ok now?

**Comment by kidwellj** [comment]
Perfect. Closing now.
