### ISSUE TITLE
Refine clustering to use Leaflet.FeatureGroup.SubGroup

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#3]
As per https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup, can we put all layers except for "Community Energy" so that all the other layers can cluster as a group

**Comment by danhillcode** [comment]
Did we agree to keep clustering as is and just change the colour of the circles? thoughts?

**Comment by kidwellj** [comment]
Yep - that's exactly right. Was actually wondering what we had in mind when we were talking about using subgroups; maybe linked in to another development goal elsewhere?
