### ISSUE TITLE
UX: graceful truncation of URL after 30 chars

### ISSUE THREAD

**Issue by kidwellj** [mapcomm/common-ground_map#9]
In the info-window long URLs don't wrap gracefully (see Abernethy & Dron Parish church as one example (just out of Blairgowrie), and there's really no reason to print the whole URL in the panel as there's already a clickable anchor there. Can we set the field to truncate output when a field is over 30 chars and add a "..." at the end to indicate that there's been a truncation?

**Comment by danhillcode** [comment]
Can you explain in person what you want to see with this.

**Comment by kidwellj** [comment]
Absolutely!

**Comment by danhillcode** [comment]
done but if you could check this.

**Comment by kidwellj** [comment]
Looking good.
